---
- hosts: all
  become: yes
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
    # perhaps reboot https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
    # epel-release needs to be installed before installing bash-completion, dbus etc.
    - yum: name=epel-release state=present
    # - name: install packages
    - yum: name={{ item }} state=present
      with_items:
        - libselinux-python
        - unzip
        - bash-completion
        - bash-completion-extras
      # for ansible nmcli http://docs.ansible.com/ansible/nmcli_module.html
        - dbus

# - hosts: labipa
#     become: yes
#     tasks:
    # - name: install ipapackages
    - yum: name={{ item }} state=present
      with_items:
        # see http://blog-ftweedal.rhcloud.com/2014/05/more-entropy-with-haveged/ requires epel-release
        - haveged
        - ipa-server
        - bind-dyndb-ldap
        - ipa-server-dns
    # setenforce 0;sed -i "s/SELINUX=enforcing/SELINUX=permissive/g" /etc/sysconfig/selinux
    - selinux: policy=targeted state=permissive
    - hostname: name=labipa.example.com
    # - name: add labipa to hosts file # echo $'192.168.4.200 labipa.example.com ipa' >> /etc/hosts
    - lineinfile: dest=/etc/hosts line="192.168.4.200 labipa.example.com ipa"
    - name: ensure firewall is running (and enable it at boot) # systemctl start firewalld
      service: name=firewalld state=started enabled=yes
    - name: open firewall # for i in http https ldap ldaps kerberos kpasswd dns ntp; do firewall-cmd --permanent --add-service $i; done
      firewalld: service={{ item }} permanent=true state=enabled # http://docs.ansible.com/ansible/firewalld_module.html
      with_items:
        - http
        - https
        - ldap
        - ldaps
        - kerberos
        - kpasswd
        - dns
        - ntp
    - service: name=haveged state=started enabled=yes
    - name: test ipa.service
      command: systemctl show ipa.service
      register: ipastatebefore
    # - name: test ipastate
    #   register:
    #
    # - debug: var=ipastate verbosity=1
    - name: install FreeIPA # see http://adam.younglogic.com/2015/06/install-freeipa-ansible/ & commandline https://www.mankier.com/1/ipa-server-install#Options SHA1withRSA to make quicker
      command: ipa-server-install -U -r EXAMPLE.COM -p password -a password --setup-dns --no-ui-redirect --ca-signing-algorithm SHA1withRSA --forwarder 10.0.2.3
    # --auto-reverse # not supported in v4.2
    # --auto-forwarders # not supported in v4.2
    # with --forwarder 10.0.2.3 DNSSEC works doesn't work, with --forwarder 8.8.8.8 DNSSEC does works
#
# - server1:
